### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by jinu-ahn** [SpringTeam10/crawling#1]
### 작성자
안진우
### 버그 발생 일시 (ex. xxxx-xx-xx, HH:MM)
2022-09-19, 17:03
### 버그 유형 (ex. 컴파일 에러, 논리적 에러)
컴파일 에러
### 버그 발생 위치
게시글 포스팅 부분
### 버그 설명
이미지 올라가지 않음

**Comment by JinKyong** [comment]
댓글
